# -*- coding: utf-8 -*-
"""widgets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwWc3IIybeN5pMzSlB8JaHEvsZ-TivVr
"""

import ipywidgets as widgets
from IPython.display import display

name_widget = widgets.Text(
    value="Manjusri",
    description="Name:"
)

# Display the widget
display(name_widget)

import ipywidgets as widgets
from IPython.display import display
dept_widget = widgets.Dropdown(
    options=["IT", "HR", "Finance"],
    value="IT",
    description="Dept:"
)
display(dept_widget)

import ipywidgets as widgets
from IPython.display import display

salary_slider = widgets.IntSlider(
    value=60000,
    min=30000,
    max=100000,
    step=5000,
    description="Salary:"
)

display(salary_slider)

import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description="Show Values")

def on_button_click(b):
    print("Name:", name_widget.value)
    print("Department:", dept_widget.value)
    print("Salary:", salary_slider.value)

button.on_click(on_button_click)

display(button)



