// 1. Display all customers
db.customers.find()

// 2. Display all products
db.products.find()

// 3. Display all orders
db.orders.find()

// 4. Show all customers from Hyderabad
db.customers.find({ city: "Hyderabad" })

// 5. Show all Electronics products
db.products.find({ category: "Electronics" })

// 6. Show products whose price is greater than 30000
db.products.find({ price: { $gt: 30000 } })

// 7. Show orders where quantity is greater than 1
db.orders.find({ quantity: { $gt: 1 } })

// 8. Display products sorted by price descending
db.products.find().sort({ price: -1 })

// 9. Display customers sorted alphabetically
db.customers.find().sort({ name: 1 })

// 10. Count the total number of orders
db.orders.countDocuments()

// 11. Find the average price of products
db.products.aggregate([
  { $group: { _id: null, avgPrice: { $avg: "$price" } } }
])

// 12. Find the maximum product price
db.products.aggregate([
  { $group: { _id: null, maxPrice: { $max: "$price" } } }
])

// 13. Find the total quantity ordered per product
db.orders.aggregate([
  { $group: { _id: "$product_id", totalQuantity: { $sum: "$quantity" } } }
])

// 14. Display orders along with customer details
db.orders.aggregate([
  {
    $lookup: {
      from: "customers",
      localField: "customer_id",
      foreignField: "customer_id",
      as: "customerDetails"
    }
  }
])

// 15. Display orders along with product details
db.orders.aggregate([
  {
    $lookup: {
      from: "products",
      localField: "product_id",
      foreignField: "product_id",
      as: "productDetails"
    }}])

// 16. Display customer name and products they ordered
db.orders.aggregate([
  {
    $lookup: {
      from: "customers",
      localField: "customer_id",
      foreignField: "customer_id",
      as: "customerDetails"
    }
  },
  {
    $lookup: {
      from: "products",
      localField: "product_id",
      foreignField: "product_id",
      as: "productDetails"
    }
  },
  {
    $project: {
      _id: 0,
      customerName: { $arrayElemAt: ["$customerDetails.name", 0] },
      productName: { $arrayElemAt: ["$productDetails.name", 0] }
    }
  }
])

// 17. Display product name and total quantity sold
db.orders.aggregate([
  {
    $group: {
      _id: "$product_id",
      totalQuantity: { $sum: "$quantity" }
    }
  },
  {
    $lookup: {
      from: "products",
      localField: "_id",
      foreignField: "product_id",
      as: "productDetails"
    }
  },
  {
    $project: {
      _id: 0,
      productName: { $arrayElemAt: ["$productDetails.name", 0] },
      totalQuantity: 1
    }
  }
])

// 18. Calculate total revenue per product
db.orders.aggregate([
  {
    $lookup: {
      from: "products",
      localField: "product_id",
      foreignField: "product_id",
      as: "productDetails"
    }
  },
  {
    $project: {
      product_id: 1,
      revenue: {
        $multiply: ["$quantity", { $arrayElemAt: ["$productDetails.price", 0] }]
      },
      productName: { $arrayElemAt: ["$productDetails.name", 0] }
    }
  },
  {
    $group: {
      _id: "$product_id",
      productName: { $first: "$productName" },
      totalRevenue: { $sum: "$revenue" }
    }
  }
])

// 19. Calculate total revenue generated by each customer
db.orders.aggregate([
  {
    $lookup: {
      from: "products",
      localField: "product_id",
      foreignField: "product_id",
      as: "productDetails"
    }
  },
  {
    $lookup: {
      from: "customers",
      localField: "customer_id",
      foreignField: "customer_id",
      as: "customerDetails"
    }
  },
  {
    $project: {
      customer_id: 1,
      customerName: { $arrayElemAt: ["$customerDetails.name", 0] },
      revenue: {
        $multiply: ["$quantity", { $arrayElemAt: ["$productDetails.price", 0] }]
      }
    }
  },
  {
    $group: {
      _id: "$customer_id",
      customerName: { $first: "$customerName" },
      totalRevenue: { $sum: "$revenue" }
    }
  }
])

// 20. Find the most sold product
db.orders.aggregate([
  {
    $group: {
      _id: "$product_id",
      totalQuantity: { $sum: "$quantity" }
    }
  },
  { $sort: { totalQuantity: -1 } },
  { $limit: 1 },
  {
    $lookup: {
      from: "products",
      localField: "_id",
      foreignField: "product_id",
      as: "productDetails"
    }
  },
  {
    $project: {
      _id: 0,
      productName: { $arrayElemAt: ["$productDetails.name", 0] },
      totalQuantity: 1
    }
  }
])
